#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        O 0.08617900000000001 0.316258 0.001593 
        H 0.991541 -0.049163 -0.005145 
        H -0.032639 0.867526 0.798933 
        H -0.04508 0.865379 -0.79538 
    End
    Charge 1
    BondOrders
         1 2 1.0
         1 3 1.0
         4 1 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        Hybrid PBE0
    End
    Relativity
        Level Spin-Orbit
        Formalism X2C
        SpinOrbitMagnetization NonCollinear
    End
EndEngine
eor

