#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        N -3.1e-05 -7.1e-05 -0.0 
        O 2.1e-05 0.621803 1.077017 
        O 2.1e-05 0.621803 -1.077017 
        O -1.2e-05 -1.243535 0.0 
    End
    Charge -1
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        Hybrid PBE0
    End
    Relativity
        Level Spin-Orbit
        Formalism X2C
        SpinOrbitMagnetization NonCollinear
    End
EndEngine
eor

