#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        O 0.0 0.273405 -0.0 
        H 0.0 0.863298 0.7600980000000001 
        H 0.0 0.863298 -0.7600980000000001 
    End
    BondOrders
         1 2 1.0
         1 3 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        Hybrid PBE0
    End
    Relativity
        Level Spin-Orbit
        Formalism X2C
        SpinOrbitMagnetization NonCollinear
    End
EndEngine
eor

